spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/krastevs_gym_spring_boot_thymeleaf_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #  sql:
  #      init:
  #        mode: never
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

app:
  default:
    admin:
      password: ${db_password}

forex:
  api:
    key: ${FOREX_API_KEY:}
    url: "https://openexchangerates.org/api/latest.json?app_id={app_id}"
    base: "USD"

activity:
  api:
    baseUrl: "http://localhost:8081"


# To generate a new secret key, go to util/HmacShaUtil.java and run the main method
jwt:
    secret: ${JWT_SECRET:d2aUj+XLQy8SEEE/nCw7LW3OpCKuPcycveYiU0tQsFwp1fDxC1GcTx5Vrgi/BBmlFOyuITNrc5Tt3Zj2Jec/Zw==}
    expiration: ${JWT_EXPIRATION:86400}

#server:
#  error:
#    whitelabel:
#      enabled: false

#server:
#  error:
#    include-stacktrace: always

#spring:
#    application:
#        name: krastevs-gym
#    thymeleaf:
#        cache: false
#        check-template-location: true
#        prefix: file:./src/main/resources/templates/