spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/krastevs_gym_spring_boot_thymeleaf_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER:${db_username}}
    password: ${MYSQL_PASSWORD:${db_password}}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #  sql:
  #      init:
  #        mode: never
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

app:
  default:
    admin:
      password: ${ADMIN_PASSWORD:V170sh@229O}

forex:
  api:
    key: ${FOREX_API_KEY:}
    url: "https://openexchangerates.org/api/latest.json?app_id={app_id}"
    base: "USD"
  init-ex-rates: ${INIT_EX_RATES:false}

activity:
  api:
    baseUrl: "${ACTIVITIES_BASE_URL:http://localhost:8081/api/v1}"


# To generate a new secret key, go to util/HmacShaUtil.java and run the main method
jwt:
  secret: ${JWT_SECRET:d2aUj+XLQy8SEEE/nCw7LW3OpCKuPcycveYiU0tQsFwp1fDxC1GcTx5Vrgi/BBmlFOyuITNrc5Tt3Zj2Jec/Zw==}
  expiration: ${JWT_EXPIRATION:86400}


timezone: Europe/Berlin


#server:
#  error:
#    whitelabel:
#      enabled: false

#server:
#  error:
#    include-stacktrace: always

#spring:
#    application:
#        name: krastevs-gym
#    thymeleaf:
#        cache: false
#        check-template-location: true

#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#    com:
#      todorkrastev:
#        krastevsgym: DEBUG
#        prefix: file:./src/main/resources/templates/

logging:
  level:
    org:
      springframework:
        boot:
          context: DEBUG