spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/krastevs_gym_spring_boot_thymeleaf_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  sql:
#      init:
#        mode: never
  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

forex:
  api:
    key: ${FOREX_API_KEY:}
    url: "https://openexchangerates.org/api/latest.json?app_id={app_id}"
    base: "USD"

#spring:
#    application:
#        name: krastevs-gym
#    thymeleaf:
#        cache: false
#        check-template-location: true
#        prefix: file:./src/main/resources/templates/